--3)A quantidade vendas do carro Uno por cliente:
SELECT CLICODIGO, CLINOME, CARCODIGO, CARMODELO, COUNT(*) AS QUANTIDADE_VENDAS
  FROM TAIF.TBVENDA
  JOIN TAIF.TBCARRO
 USING (CARCODIGO)
  JOIN TAIF.TBCLIENTE
 USING (CLICODIGO)
 WHERE CARMODELO ILIKE 'UNO'
 GROUP BY CLICODIGO, CLINOME, CARCODIGO, CARMODELO
 ORDER BY QUANTIDADE_VENDAS