--5) Os clientes sorteados:
SELECT SEQ, CLICODIGO, CLINOME, CLICPF
  FROM (
		SELECT CLICODIGO, CLINOME, CLICPF, ROW_NUMBER() OVER (ORDER BY VENDATA) AS SEQ
		  FROM TAIF.tbvenda A
		  JOIN TAIF.TBCLIENTE
		 USING (CLICODIGO)
		  JOIN TAIF.TBCARRO
		 USING (CARCODIGO)
		 WHERE SUBSTRING(CLICPF, 1,1) = '0'
		   AND EXTRACT (YEAR FROM CARDATALANCAMENTO) = 2021
		   AND NOT EXISTS ( SELECT CLICODIGO, COUNT(*)
							  FROM TAIF.TBVENDA B
							  JOIN TAIF.TBCARRO
							 USING (CARCODIGO)
							 WHERE CARMODELO ILIKE 'MAREA'
							   AND A.CLICODIGO = B.CLICODIGO
							 GROUP BY CLICODIGO
							HAVING COUNT(*) > 1 )
		 ORDER BY VENDATA
		) WHERE SEQ <= 15